# Site settings
title: The Midwest Sing & Stomp
email: tsmacdonald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Midwest Sing & Stomp is a celebration of folk music and dance
  featuring two stages with contra, square, blues, and cajun dancing and
  traditional Irish, Scottish, old-time American, Swedish, and other music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://singandstomp.com" # the base hostname & protocol for your site
facebook_username: MWSingandStomp
github_username:
bootstrap:
  assets: true

# Build settings
markdown: kramdown
gems:
  - jekyll-bootstrap-sass
